# packages needed for analyses

library(tidyverse)
library(terra)
library(sf)
library(geodata)
library(ENMTools)
library(corrplot)
library(devtools)
#devtools::install_version("taxize", version = "0.9.100.1", repos = "http://cran.us.r-project.org")
library(taxize)
library(rgbif)
library(CoordinateCleaner)
library(whitebox)
library(fuzzySim)
library(maxnet)
library(gam)
library(blockCV)
#devtools::install_github("jamiemkass/ENMeval")
library(ENMeval)
library(rJava)
library(dismo)
library(RColorBrewer)
library(exactextractr)
library(ggrepel)
library(patchwork)
#devtools::install_github("Rimagination/ggmapcn", force = TRUE)
library(ggmapcn)
